-- 0011_ai_enhancements.sql
--
-- Phase 1 of the AI organizer modernization: richer model output and
-- review-state tracking. All columns are nullable / have defaults so the
-- existing pending queue stays valid without back-filling.

-- Topic phrase generated by the model for a bookmark, used for in-job
-- clustering and post-run topic distribution visualisation.
ALTER TABLE tag_suggestions ADD COLUMN topic TEXT;

-- Whether the model explicitly flagged this proposal as uncertain and
-- recommended human review. Distinct from confidence: a tag can be
-- high-confidence in a novel context and still need a human sanity check.
ALTER TABLE tag_suggestions ADD COLUMN needs_review INTEGER NOT NULL DEFAULT 0;

-- Index for building per-job topic aggregates efficiently.
CREATE INDEX IF NOT EXISTS idx_sugg_job_topic
  ON tag_suggestions (job_id, topic)
  WHERE status = 'pending';
